finalytics-0.1.1

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -23,9 +23,22 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        target: [x86_64, x86, aarch64, armv7, s390x, ppc64le]
+        target: [ x86_64, x86, aarch64, armv7, s390x, ppc64le ]
     steps:
       - uses: actions/checkout@v3
+      - name: Install Linux Build Dependencies
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y build-essential pkg-config libssl-dev
+      - name: Find and Set OpenSSL Environment Variable
+        run: |
+          openssl_path=$(which openssl)
+          if [ -n "$openssl_path" ]; then
+            export OPENSSL_DIR=$(dirname $(dirname $openssl_path))
+          else
+            echo "OpenSSL not found. Make sure it's installed."
+            exit 1
+          fi
       - uses: actions/setup-python@v4
         with:
           python-version: '3.10'
